# Ingest data to database for Barrow mass balance data.
# 
# Database config
database:
  host: "localhost"
  name: "barrow_mass_balance"
  port: "27017"
  raw_data_coll: "mass_balance_raw"
  final_data_coll: "mass_balance_data"
  user: ""
  password: ""

# Import options
csv:
  header: true
  delimiter: ","

# Platform Information
platform:
  name: "Barrow Mass Balance"
  agency: "Sea Ice Group UAF GI"
  platform_metadata: "http://gina.metadata.alaska.edu"
  geo_location: "156.5427° W, 71.36427° N"
  license: "6"
  permissions: "0"
  authority: "Andy Mahoney"

# Sensor Information
sensor:
  -
    label: ""
    datum: ""
    metadata:

# Process the data
process:
  -

# Alerts
alerts:
  -

