# Generate graph and put image in RailsRoot/graphs/platform_slug
# Each image is named by the graph id
# a thumbnail image is generated by RMagick and placed in the same directory
class GraphImageProcessor
  include RvgGraph
  include Magick
  @queue = :graph_image

  def self.perform(slug, graph_id)
    platform = Platform.where( slug: slug ).first
    graph = platform.graphs.find(graph_id)
    # These dates need to be smarter
    starts_at = "2011-06-04 00:00:00 UTC"
    ends_at = "2011-06-06 00:00:00 UTC"

    path = Rails.root.join('graphs', slug)
    unless File.exists?(path)
      Dir.mkdir(path)
    end
    file = path.join("#{graph_id}.jpg")
    puts "Creating Graph, output to #{file}"

    newgraph = Ginagraph.new(slug, graph, starts_at, ends_at)
    newgraph.draw_data(newgraph.template["graph_data"]) if newgraph.template["graph_data"]
    newgraph.draw_border(newgraph.template["border"]) if newgraph.template["border"]
    newgraph.save(file)
    thumbfile = path.join("#{graph.id}_thumb.jpg")
    img = Image.read(file).first
    thumb = img.resize_to_fit(200)
    thumb.write(thumbfile)
    puts "Done!"
  end
end