# Generate graph and put image in RailsRoot/graphs/platform_slug
# Each image is named by the graph id
# a thumbnail image is generated by RMagick and placed in the same directory
class GraphProcessor
  include RvgGraph
  include Magick
  @queue = :graph_processor

  def self.perform(slug, graph_id, starts_at, ends_at, output_name)
    puts "Creating Graph, output to #{output_name}"

    graph = Graph.new(slug, graph_id, DateTime.parse(starts_at), DateTime.parse(ends_at))

    graph.draw
    graph.save(output_name)
  end
end